models = {
    "gpt-4.1-mini": {
        "id": "gpt-4.1-mini",
        "name": "gpt-4.1-mini",
        "object": "model",
        "created": 1748976485,
        "owned_by": "Azure",
        "modalities": {"input": ["text", "image"]},
    },
    "gpt-4.1": {
        "id": "gpt-4.1",
        "name": "gpt-4.1",
        "object": "model",
        "created": 1748976485,
        "owned_by": "Azure",
        "modalities": {"input": ["text", "image"]},
    },
    "qwen2.5-coder": {
        "id": "qwen2.5-coder-32b-instruct:int8",
        "name": "qwen2.5-coder",
        "object": "model",
        "created": 1748976485,
        "owned_by": "Scaleway",
        "modalities": {"input": ["text"]},
    },
    "llama-3.3": {
        "id": "llama-3.3-70b-instruct-fp8-fast",
        "name": "llama-3.3",
        "object": "model",
        "created": 1748976485,
        "owned_by": "Cloudflare",
        "modalities": {"input": ["text"]},
    },
    "llama-4": {
        "id": "llama-4-scout-17b-16e-instruct",
        "name": "llama-4",
        "object": "model",
        "created": 1748976485,
        "owned_by": "Cloudflare",
        "modalities": {"input": ["text"]},
    },
    "deepseek-r1": {
        "id": "deepseek-r1",
        "name": "deepseek-r1",
        "object": "model",
        "created": 1748976485,
        "owned_by": "Cloudflare",
        "modalities": {"input": ["text"]},
    },
    "deepseek-v3": {
        "id": "deepseek-v3",
        "name": "deepseek-v3",
        "object": "model",
        "created": 1748976485,
        "owned_by": "DeepSeek",
        "modalities": {"input": ["text"]},
    },
    "grok": {
        "id": "grok",
        "name": "grok",
        "object": "model",
        "created": 1748976485,
        "owned_by": "Azure",
        "modalities": {"input": ["text"]},
    },
    "codestral": {
        "id": "codestral-2501",
        "object": "model",
        "name": "codestral",
        "created": 1748976485,
        "owned_by": "mistral",
        "modalities": {"input": ["text"]},
    },
    "mistral-large": {
        "id": "mistral-large-2411",
        "name": "mistral-large",
        "object": "model",
        "created": 1748976485,
        "owned_by": "mistral",
        "modalities": {"input": ["text"]},
    },
}
